apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway

spec:
  replicas: 0
  selector:
    matchLabels:
      app: gateway

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3

  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: samnzay/gateway-service:v1.0.0
          envFrom:
            - configMapRef:
                name: gateway-configmap
            - secretRef:
                name: gateway-secret