apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap

## Config map environment variables will be present within the container.
## remember this is not meant for sensitive data like passwords!!
data:
  MYSQL_HOST: host.minikube.internal
  MYSQL_USER: auth_user
  MYSQL_DB: auth
  MYSQL_PORT: "3307"