DROP USER auth_user;
DROP DATABASE auth;
CREATE USER 'root'@'127.0.0.1:3307' IDENTIFIED BY 'secret';


CREATE DATABASE auth;

GRANT ALL PRIVILEGES ON auth.* TO 'root'@'127.0.0.1:3307';
FLUSH PRIVILEGES;

USE auth;

CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    passwrd VARCHAR(255) NOT NULL
);

INSERT INTO user (email, password) VALUES ('samnzay@gmail.com','Admin123');